defaults:
  - override hydra/launcher: submitit_slurm
  - _self_
seed: 0
eval_episodes: 5
eval_interval: 10000
online_eval_interval: 1000
batch_size: 1024
max_steps: 1000000
replay_buffer_size: 1000000
start_training: 5000
env_names: HB_BASIC
log_to_wandb: true
offline_evaluation: true
render: false
updates_per_step: 2
width_critic: 4096
width_actor: 256
depth_actor: 1
save_path: ""
disable_jit: false
v_max: 10.0
normalize: true
job_type: default
project: BRC
w_lr: 0.025
w_d: 0.9
heatmap_max_history: 500
loss_process: famo_total #mean #famo_total
warmup_epochs: 10000
use_separate_actor_grad: false
use_separate_critic_grad: false
separate_grad_every: 1
grad_process: fairgrad
last_init_str: orthogonal
balance_critic: false
log_bin_interval: 100
rollout_checkpoint_path: ""
rollout_output_dir: "./rollout_videos"
rollout_episodes: 1
rollout_temperature: 0.0
rollout_max_render_steps: 5000
rollout_render_frameskip: 4
rollout_video_fps: 15
rollout_log_to_wandb: True

wandb:
  entity: crusaderx

famo:
  famo_w_regu: 0.
  famo_kl_eps: 0.01