seed: 0
eval_episodes: 5
eval_interval: 10000
online_eval_interval: 1000
batch_size: 1024
max_steps: 1000000
replay_buffer_size: 1000000
start_training: 5000
env_names: cheetah-run
log_to_wandb: true
offline_evaluation: true
render: false
updates_per_step: 2
width_critic: 4096
width_actor: 256
depth_actor: 2
save_path: ""
disable_jit: false
v_max: 10.0
normalize: true
job_type: default
project: BRC
w_lr: 0.1
w_d: 0.001
heatmap_max_history: 500
loss_process: mean #famo_total
warmup_epochs: 10000
use_separate_actor_grad: false
use_separate_critic_grad: false
separate_grad_every: 1
grad_process: fairgrad
last_init_str: orthogonal
balance_critic: false